rules:
  - following_context: '[vn]'
    preceding_context: '^'
    replacement: 'd ə'
    segment: 'd'
  - following_context: '[d]'
    preceding_context: '^'
    replacement: 'ɡ ə'
    segment: 'ɡ'
  - following_context: '[smd]'
    preceding_context: '^'
    replacement: ''
    segment: 'j'
  - following_context: '$'
    preceding_context: ''
    replacement: 'u'
    segment: 'u j ɪ'
  - following_context: 'n'
    preceding_context: 's'
    replacement: ''
    segment: 't'
  - following_context: '$'
    preceding_context: ''
    replacement: ''
    segment: 't'
  - following_context: '$'
    preceding_context: ''
    replacement: 'u j u'
    segment: 'u j ɪ'
  - following_context: '$'
    preceding_context: ''
    replacement: 'j iː'
    segment: 'j ɛ j iː'
  - following_context: ''
    preceding_context: ''
    replacement: 'j ɛː'
    segment: 'j ɛ j ɛ'
