dialects:
  portugal:
  - following_context: ''
    preceding_context: '[^̃]+'
    replacement: 'ð'
    segment: 'd'
  - following_context: ''
    preceding_context: '[^̃]+'
    replacement: 'β'
    segment: 'b'
  - following_context: ''
    preceding_context: '[^̃]+'
    replacement: 'v'
    segment: 'b'
  - following_context: ''
    preceding_context: '[^̃]+'
    replacement: 'ɣ'
    segment: 'ɡ'
  - following_context: '$'
    preceding_context: ''
    replacement: 'o'
    segment: 'o w'
  - following_context: '$'
    preceding_context: '[td]'
    replacement: ''
    segment: 'ɨ'
  - following_context: 'ʃ'
    preceding_context: '^'
    replacement: ''
    segment: 'i'
  - following_context: '$'
    preceding_context: '[td]'
    replacement: ''
    segment: 'ɨ'
  brazil:
  - following_context: ''
    preceding_context: ''
    replacement: 'x'
    segment: 'ʁ'
  - following_context: ''
    preceding_context: ''
    replacement: 'h'
    segment: 'ʁ'
  - following_context: '$'
    preceding_context: ''
    replacement: ''
    segment: 'ɾ'
  - following_context: '$'
    preceding_context: ''
    replacement: ''
    segment: 'ʁ'
  - following_context: '$'
    preceding_context: ''
    replacement: 't e'
    segment: 'tʃ i'
  - following_context: '$'
    preceding_context: 'tʃ'
    replacement: ''
    segment: 'i'
  - following_context: '$'
    preceding_context: ''
    replacement: 'd e'
    segment: 'dʒ i'
  - following_context: '$'
    preceding_context: ''
    replacement: 'l e'
    segment: 'ʎ i'
  - following_context: '$'
    preceding_context: '[^ʒʃ]+'
    replacement: 'e'
    segment: 'i'
  - following_context: ''
    preceding_context: ''
    replacement: 'e'
    segment: 'i'
  - following_context: '$'
    preceding_context: ''
    replacement: 'o'
    segment: 'u'
  - following_context: ''
    preceding_context: ''
    replacement: 'o'
    segment: 'u'
  - following_context: '$'
    preceding_context: ''
    replacement: 'a'
    segment: 'ɐ'
  - following_context: ''
    preceding_context: ''
    replacement: 'a'
    segment: 'ɐ'
  - following_context: '$'
    preceding_context: '[ɐauoieɛjwɔɨ].'
    replacement: 'ʃ'
    segment: 's'
  - following_context: '$'
    preceding_context: '[ɐauoieɛjwɔɨ].'
    replacement: ''
    segment: 's'
  - following_context: ''
    preceding_context: '[ɐauoieɛjwɔɨ].'
    replacement: 'ʃ'
    segment: 's'
rules:
  - following_context: ''
    preceding_context: ''
    replacement: 'k w'
    segment: 'kʷ'
  - following_context: ''
    preceding_context: ''
    replacement: 'ɡ w'
    segment: 'ɡʷ'
  - following_context: '$'
    preceding_context: '[td]'
    replacement: ''
    segment: 'u'
  - following_context: '$'
    preceding_context: '[td]'
    replacement: ''
    segment: 'i'
