dialects:
  latin_america:
    - following_context: '[^ij]'
      preceding_context: ''
      replacement: 'ɲ j'
      segment: 'ɲ'
    - following_context: ''
      preceding_context: ''
      replacement: 'ʃ'
      segment: 'ʝ'
    - following_context: ''
      preceding_context: ''
      replacement: 'ʃ'
      segment: 'ɟʝ'
  spain:
    - following_context: ''
      preceding_context: ''
      replacement: 's'
      segment: 'θ'
    - following_context: '$'
      preceding_context: ''
      replacement: ''
      segment: 'θ'
rules:
  - following_context: '$'
    preceding_context: ''
    replacement: ''
    segment: 's'
  - following_context: '$'
    preceding_context: ''
    replacement: 'h'
    segment: 's'
  - following_context: '[^aiouejw]'
    preceding_context: ''
    replacement: 'h'
    segment: 's'
  - following_context: '[^aiouejw]'
    preceding_context: ''
    replacement: ''
    segment: 's'
  - following_context: '[^aiouejw]'
    preceding_context: '^'
    replacement: 'e s'
    segment: 's'
  - following_context: '[^aiouejw]'
    preceding_context: '^'
    replacement: 'e z'
    segment: 'z'
  - following_context: ''
    preceding_context: '^'
    replacement: ''
    segment: 'x'
  - following_context: '$'
    preceding_context: ''
    replacement: ''
    segment: 'ɾ'
  - following_context: '$'
    preceding_context: ''
    replacement: 'r'
    segment: 'ɾ'
  - following_context: '$'
    preceding_context: ''
    replacement: ''
    segment: '[ŋnmɲ]'
  - following_context: '$'
    preceding_context: ''
    replacement: ''
    segment: 'ð'

  - following_context: '[^aiouejw]'
    preceding_context: '[aiouejw]'
    replacement: 'r'
    segment: 'ɾ'
  - following_context: '[aiouejw]'
    preceding_context: '[^aiouejw]'
    replacement: 'r'
    segment: 'ɾ'
