-
  - a
  - aː
-
  - aw
-
  - b
-
  - c
-
  - d
-
  - dz
-
  - dʒ
-
  - ew
-
  - f
-
  - i
  - iː
-
  - j
-
  - k
-
  - l
  - l̩
-
  - m
  - m̩
-
  - n
  - n̩
-
  - o
  - oː
-
  - ow
-
  - p
-
  - r
  - r̩
-
  - r̝
-
  - r̝̊
-
  - s
-
  - t
-
  - ts
-
  - tʃ
-
  - u
  - uː
-
  - v
-
  - x
-
  - z
-
  - ŋ
-
  - ə
-
  - ɛ
  - ɛː
-
  - ɟ
-
  - ɡ
-
  - ɦ
-
  - ɪ
-
  - ɲ
-
  - ʃ
-
  - ʒ
-
  - ʔ
