-
  - a
-
  - b
-
  - d
-
  - dʒ
-
  - e
-
  - ẽ
-
  - f
-
  - i
-
  - ĩ
-
  - j
-
  - j̃
-
  - k
-
  - kʷ
-
  - l
-
  - m
-
  - n
-
  - o
-
  - õ
-
  - p
-
  - s
-
  - t
-
  - tʃ
-
  - u
-
  - ũ
-
  - v
-
  - w
-
  - w̃
-
  - x
-
  - z
-
  - ɐ
-
  - ɐ̃
-
  - ɔ
-
  - ɛ
-
  - ɡ
-
  - ɡʷ
-
  - ɫ
-
  - ɲ
-
  - ɨ
-
  - ɾ
-
  - ʁ
-
  - ʃ
-
  - ʎ
-
  - ʒ
-
  - ɣ
-
  - β
-
  - ð
-
  - h
-
  - r
-
  - χ
