-
  - a
  - aː
  - aː˦˨
  - aː˨˦
  - a˦˨
  - a˨˦
-
  - b
-
  - d
-
  - dʑ
-
  - dʒ
-
  - e
  - eː
  - eː˦˨
  - eː˨˦
  - e˦˨
  - e˨˦
-
  - f
-
  - i
  - iː
  - iː˦˨
  - iː˨˦
  - i˦˨
  - i˨˦
-
  - j
-
  - k
-
  - l
-
  - m
-
  - n
-
  - o
  - oː
  - oː˦˨
  - oː˨˦
  - o˦˨
  - o˨˦
-
  - p
-
  - r
  - rː
  - r̩
  - r̩ː˦˨
  - r̩ː˨˦
  - r̩˦˨
  - r̩˨˦
-
  - s
-
  - t
-
  - ts
-
  - tɕ
-
  - tʃ
-
  - u
  - uː
  - uː˦˨
  - uː˨˦
  - u˦˨
  - u˨˦
-
  - v
-
  - x
-
  - z
-
  - ɡ
-
  - ɲ
-
  - ʃ
-
  - ʎ
-
  - ʒ
