-
  - b
-
  - c
-
  - d̪
-
  - f
-
  - v
-
  - j
-
  - k
-
  - l
-
  - ʎ
-
  - m
-
  - ɱ
-
  - n
-
  - p
-
  - r
-
  - s
-
  - h
-
  - z
-
  - tʃ
-
  - t̪
-
  - w
-
  - x
-
  - ç
-
  - ð
-
  - ŋ
-
  - ɟ
-
  - ɟʝ
-
  - ɡ
-
  - ɣ
-
  - ɲ
-
  - ɾ
-
  - ʃ
-
  - θ
-
  - ʝ
-
  - β
-
  - a
-
  - ã
-
  - o
-
  - õ
-
  - e
-
  - ẽ
-
  - i
-
  - ĩ
-
  - u
-
  - ũ
